sudo: required

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('changeme');"

language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
 - pip install -U --force-reinstall pip
 - pip install -U --force-reinstall setuptools
 - pip install -r requirements.txt
# command to run tests
script: py.test --cov=.
dist: trusty
after_success: coveralls
