services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'

language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
 - pip install -U pip
 - pip install -U pytest
 - pip install -r requirements.txt
# command to run tests
script: py.test --cov=.
dist: trusty
after_success: coveralls
