FROM python:3.12.3-bullseye

RUN apt install tzdata

ADD requirements.txt /

RUN pip install --upgrade pip && pip install --no-input --upgrade --force-reinstall -r requirements.txt

ENV TZ=Europe/Stockholm

COPY . /app

RUN chmod 755 /app/start_app.sh

WORKDIR /app

EXPOSE 5555

CMD ["/bin/bash", "-c", "python /app/manage.py migrate && celery -A mii_celery flower"]