# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mii_rss', '0004_auto_20151222_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
