def mock_get_movie_name(_, name, year):
    data = {
        'Thor/2011': {u'total_results': 7, u'total_pages': 1, u'page': 1, u'results': [{u'poster_path': u'/bIuOWTtyFPjsFDevqvF3QrD1aun.jpg', u'title': u'Thor', u'release_date': u'2011-05-06', u'popularity': 10.6783505729882, u'original_title': u'Thor', u'backdrop_path': u'/siiHsWPaP2r8hqPiQsry61gCjGY.jpg', u'vote_count': 2587, u'adult': False, u'vote_average': 6.3, u'id': 10195}, {u'poster_path': u'/5uGaqAnt0RQ87uKy8UlRDNrL2jY.jpg', u'title': u"Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer", u'release_date': u'2011-10-25', u'popularity': 0.959893741398338, u'original_title': u"Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer", u'backdrop_path': u'/wdMq7F5Cr1DGg8ioNPZvWxqQer4.jpg', u'vote_count': 9, u'adult': False, u'vote_average': 7.2, u'id': 76535}, {u'poster_path': u'/jmszqWpP6JehbetACrTwo0GdGcT.jpg', u'title': u'Thor: Tales of Asgard', u'release_date': u'2011-05-17', u'popularity': 0.736035603384104, u'original_title': u'Thor: Tales of Asgard', u'backdrop_path': u'/4itWzlN3GnvsEfGPzUlqxVxpdrz.jpg', u'vote_count': 12, u'adult': False, u'vote_average': 6.7, u'id': 63686}, {u'poster_path': u'/9aWnlKIb6ODpkNJ6GJIjwx1u3rS.jpg', u'title': u'Legends of Valhalla: Thor', u'release_date': u'2011-10-14', u'popularity': 0.460864067533271, u'original_title': u'Hetjur Valhallar - \xde\xf3r', u'backdrop_path': u'/bcLk7JMhOK2wPkGl1lUbamKNSRJ.jpg', u'vote_count': 1, u'adult': False, u'vote_average': 7.0, u'id': 106631}, {u'poster_path': u'/eeNr3zcHDL5RAkdmTXXGbew8kNZ.jpg', u'title': u'Vicky and the Treasure of the Gods', u'release_date': u'2011-09-28', u'popularity': 0.318767802196951, u'original_title': u'Wickie auf gro\xdfer Fahrt', u'backdrop_path': u'/wZsZ1Gis6YFVaXw3mO1vbulMs5c.jpg', u'vote_count': 2, u'adult': False, u'vote_average': 5.8, u'id': 80109}, {u'poster_path': u'/kK7TQYOkmY6SiFfqbPAVxajfdCk.jpg', u'title': u'Adventures of Thunderstorm: Return of Thor', u'release_date': u'2012-05-01', u'popularity': 0.218437518435504, u'original_title': u'Adventures of Thunderstorm: Return of Thor', u'backdrop_path': u'/9tbkTZ2GDbn5igGPc5DO86GyYlf.jpg', u'vote_count': 1, u'adult': False, u'vote_average': 8.0, u'id': 103696}, {u'poster_path': u'/gh8WcgcrIWDQeFbRawuFiRGvqvu.jpg', u'title': u'Almighty Thor', u'release_date': u'2011-05-07', u'popularity': 0.152731940408473, u'original_title': u'Almighty Thor', u'backdrop_path': u'/8OUV8xYpycEc6dChZDmPUx7vmx6.jpg', u'vote_count': 2, u'adult': False, u'vote_average': 2.0, u'id': 63736}]},
        'Thor The Dark World/None': {u'total_results': 1, u'total_pages': 1, u'page': 1, u'results': [{u'poster_path': u'/aROh4ZwLfv9tmtOAsrnkYTbpujA.jpg', u'title': u'Thor: The Dark World', u'release_date': u'2013-11-08', u'popularity': 15.0506195551349, u'original_title': u'Thor: The Dark World', u'backdrop_path': u'/3FweBee0xZoY77uO1bhUOlQorNH.jpg', u'vote_count': 916, u'adult': False, u'vote_average': 7.1, u'id': 76338}]},
    }
    return data['%s/%s' % (name, year)]

def mock_get_movie_imdb_id(_, id):
    data = {
        '10195': {u'poster_path': u'/bIuOWTtyFPjsFDevqvF3QrD1aun.jpg', u'production_countries': [{u'iso_3166_1': u'US', u'name': u'United States of America'}], u'revenue': 444115007, u'overview': u"Against his father Odin's will, The Mighty Thor -a powerful but arrogant warrior god -recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.", u'id': 10195, u'genres': [{u'id': 28, u'name': u'Action'}, {u'id': 12, u'name': u'Adventure'}, {u'id': 14, u'name': u'Fantasy'}], u'title': u'Thor', u'tagline': u'Two worlds. One hero.', u'vote_count': 2587, u'homepage': u'http://thor.marvel.com/', u'belongs_to_collection': {u'backdrop_path': u'/3KL8UNKFWgIKXzLHjwY0uwgjzYl.jpg', u'poster_path': u'/7vx64r9HS57yz2T53i31SdmqdEi.jpg', u'id': 131296, u'name': u'Thor Collection'}, u'status': u'Released', u'spoken_languages': [{u'iso_639_1': u'en', u'name': u'English'}], u'imdb_id': u'tt0800369', u'adult': False, u'backdrop_path': u'/siiHsWPaP2r8hqPiQsry61gCjGY.jpg', u'production_companies': [{u'name': u'Marvel Studios', u'id': 420}, {u'name': u'Marvel Entertainment', u'id': 7505}], u'release_date': u'2011-05-06', u'popularity': 10.6783505729882, u'original_title': u'Thor', u'budget': 150000000, u'vote_average': 6.3, u'runtime': 115},
        '76338': {u'poster_path': u'/aROh4ZwLfv9tmtOAsrnkYTbpujA.jpg', u'production_countries': [{u'iso_3166_1': u'US', u'name': u'United States of America'}], u'revenue': 479765000, u'overview': u'Thor fights to restore order across the cosmos\u2026 but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.', u'id': 76338, u'genres': [{u'id': 28, u'name': u'Action'}, {u'id': 12, u'name': u'Adventure'}, {u'id': 14, u'name': u'Fantasy'}], u'title': u'Thor: The Dark World', u'tagline': u'Delve into the darkness', u'vote_count': 916, u'homepage': u'http://marvel.com/thor', u'belongs_to_collection': {u'backdrop_path': u'/3KL8UNKFWgIKXzLHjwY0uwgjzYl.jpg', u'poster_path': u'/7vx64r9HS57yz2T53i31SdmqdEi.jpg', u'id': 131296, u'name': u'Thor Collection'}, u'status': u'Released', u'spoken_languages': [{u'iso_639_1': u'en', u'name': u'English'}], u'imdb_id': u'tt1981115', u'adult': False, u'backdrop_path': u'/3FweBee0xZoY77uO1bhUOlQorNH.jpg', u'production_companies': [{u'name': u'Marvel Studios', u'id': 420}], u'release_date': u'2013-11-08', u'popularity': 15.0506195551349, u'original_title': u'Thor: The Dark World', u'budget': 170000000, u'vote_average': 7.1, u'runtime': 112},
    }
    return data['%s' % id]
