# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mii_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question_type',
            field=models.CharField(choices=[('actor', 'actor'), ('story', 'store'), ('overall', 'overall'), ('director', 'director')], max_length=50),
        ),
    ]
