# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mii_unpacker', '0002_auto_20150620_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpacked',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
