# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mii_unpacker', '0003_auto_20151222_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpacked',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
