# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0003_jsonkeyvalue_key_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonkeyvalue',
            name='key_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
