# Generated by Django 4.1.6 on 2023-02-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0004_auto_20161211_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonkeyvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
