# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mii_sorter', '0008_auto_20150719_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexRenaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(max_length=255)),
                ('new', models.CharField(max_length=255)),
            ],
        ),
    ]
