# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mii_sorter', '0010_auto_fix_folder_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialHandling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
