# Generated by Django 4.1.6 on 2023-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mii_sorter', '0012_alter_episode_id_alter_movie_id_alter_movie_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='folder_path',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='folder_path',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
